on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number'
        required: true
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get PR Details
      id: pr_details
      run: |
        pr_number="${{ github.event.inputs.pr_number }}"
        pr_details=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number")
        pr_title=$(echo "$pr_details" | jq -r '.title')
        pr_author=$(echo "$pr_details" | jq -r '.user.login')
        pr_url=$(echo "$pr_details" | jq -r '.html_url')
        echo "::set-output name=pr_title::$pr_title"
        echo "::set-output name=pr_author::$pr_author"
        echo "::set-output name=pr_url::$pr_url"
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: testchannel
        SLACK_TITLE: 'PR Merged: ${{ steps.pr_details.outputs.pr_title }}'
        SLACK_MESSAGE: 'Author: ${{ steps.pr_details.outputs.pr_author }}\nBody: ${{ steps.pr_details.outputs.pr_body }}'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: 'Powered by Dibbly Inc.'

    - name: Send Hello World Message
      run: |
        author="${{ steps.pr_details.outputs.pr_author }}"
        pr_name="${{ steps.pr_details.outputs.pr_title }}"
        pr_link="${{ steps.pr_details.outputs.pr_url }}"
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Author: $author\nPR Name: $pr_name\nPR Link: $pr_link\"}" "${{ secrets.SLACK_WEBHOOK }}"