on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request #'
        required: true
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: testchannel
        SLACK_TITLE: 'Commit Message'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: 'Powered by Dibbly Inc.'

