on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send Slack Notification using curl
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' ${{ secrets.SLACK_WEBHOOK }}
    # - name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_CHANNEL: testchannel
    #     SLACK_ICON: https://github.com/rtCamp.png?size=48
    #     SLACK_MESSAGE: 'Post Content :rocket:'
    #     SLACK_TITLE: Post Title
    #     SLACK_USERNAME: Dibblyy
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}